#!/bin/bash

# Set the ROOM_ID & AUTH_TOKEN variables below.
# Further instructions at https://www.hipchat.com/docs/apiv2/auth

#ITM-Linux-Internal
ROOM_ID=241

#EnrolldNotification
AUTH_TOKEN=kk6fWx55a2ENqApq2bw6CYCUlAgVUXs5YlZgfrAp

curl -H "Content-Type: application/json" \
     -X POST \
     -d "{\"color\": \"red\", \"notify\": \"true\", \"message_format\": \"text\", \"message\": \"$MESSAGE\" }" \
     https://hipchat/v2/room/$ROOM_ID/notification?auth_token=$AUTH_TOKEN
